### ISSUE TITLE
Guest login

### ISSUE THREAD

**Issue by himanshu007-creator** [CERN/slides#3]
There should be a provision for guest login, to try how this platform works , because i tried login via google,github, linkedin and facebook, 
But all of them proved of no use.

**Comment by abhilipsasahoo03** [comment]
> There should be a provision for guest login, to try how this platform works , because i tried login via google,github, linkedin and facebook, But all of them proved of no use.

Facing the same issue. 
![IMG_20220131_203448](https://user-images.githubusercontent.com/80174214/151817943-a89f1d36-eb11-49e6-b177-43ac438e7414.jpg)

**Comment by OlegSchwann** [comment]
Ideally, make the cern.ch/slides page public.

**Comment by giacomd** [comment]
The cern.ch/slides service has been decommissioned, so we are archiving this repository.
